# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - elideus-metal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://elideus.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f9aa42f3e0c74f45bc8951d5984c696d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5ffe4473f06c4d3fa5ecc5cc1e7e78a5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: elideus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f9aa42f3e0c74f45bc8951d5984c696d }}/elideus/elideus-metal:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elideus-metal'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bf4a907a071f430bb357bcebf29654c2 }}
        images: 'elideus.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f9aa42f3e0c74f45bc8951d5984c696d }}/elideus/elideus-metal:${{ github.sha }}'